"""Remove total_amount from income model

Revision ID: 23867a9810c5
Revises: 95de38c12724
Create Date: 2024-01-07 18:19:28.826342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23867a9810c5'
down_revision = '95de38c12724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
