"""Initial migration

Revision ID: 27c679a4d581
Revises: 
Create Date: 2024-05-08 18:13:35.079733

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "27c679a4d581"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    category_table = op.create_table(
        "category",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.Column("color", sa.String(length=6), nullable=False),
        sa.Column(
            "default_income_percent",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.bulk_insert(
        category_table,
        [
            {"code": "GOD", "title": "God", "color": "8FAADC"},
            {"code": "SAVING", "title": "Save", "color": "FFE699"},
            {"code": "SPENDING", "title": "Spend", "color": "F4B183"},
            {"code": "OTHER", "title": "Other", "color": "ffffff"},
        ],
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column(
            "color", sa.String(length=6), server_default="6C757D", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expense",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("notes", sa.String(length=4000), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("category_code", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_code"],
            ["category.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "income",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=4000), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("category_code", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_code"],
            ["category.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expense_tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("expense_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expense.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expense_tag")
    op.drop_table("income")
    op.drop_table("expense")
    op.drop_table("tag")
    op.drop_table("category")
    # ### end Alembic commands ###
