"""Add color field for tags

Revision ID: 4700afdb8c17
Revises: 23867a9810c5
Create Date: 2024-01-13 11:38:41.776824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4700afdb8c17"
down_revision = "23867a9810c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "color", sa.String(length=6), nullable=False, server_default="6C757D"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_column("color")

    # ### end Alembic commands ###
