"""Add notes field to Income model

Revision ID: 54ee4eb3d25e
Revises: 4700afdb8c17
Create Date: 2024-01-24 19:47:42.589469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ee4eb3d25e'
down_revision = '4700afdb8c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=4000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
