"""Remove default_income_percent field from Category model

Revision ID: 57f465792829
Revises: 27c679a4d581
Create Date: 2025-06-21 10:25:35.603429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f465792829'
down_revision: Union[str, None] = '27c679a4d581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'default_income_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('default_income_percent', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###
