"""Add repeat_id column to Expense model

Revision ID: ad6b58ee2550
Revises: c40edae0398a
Create Date: 2025-06-21 11:17:24.131001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6b58ee2550'
down_revision: Union[str, None] = 'c40edae0398a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('repeat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'repeat_id')
    # ### end Alembic commands ###
