"""Remove 'RepeatExpense'

Revision ID: bedef1bfac42
Revises: ad6b58ee2550
Create Date: 2025-10-23 19:27:59.931279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bedef1bfac42'
down_revision: Union[str, None] = 'ad6b58ee2550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repeat_expense')
    op.drop_column('expense', 'repeat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('repeat_id', sa.INTEGER(), nullable=True))
    op.create_table('repeat_expense',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('expense_id', sa.INTEGER(), nullable=False),
    sa.Column('repeat_scale', sa.VARCHAR(length=10), nullable=False),
    sa.Column('repeat_increment', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
