"""Add default income percent field to Category model

Revision ID: cc9c9e125e89
Revises: 54ee4eb3d25e
Create Date: 2024-01-24 19:57:17.878720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9c9e125e89'
down_revision = '54ee4eb3d25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_income_percent', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('default_income_percent')

    # ### end Alembic commands ###
